#include "framework.h"
#include "Specific/Input/Keys.h"

namespace TEN::Input
{
	static const auto KEY_NAME_MAP = std::unordered_map<int, std::string>
	{
		{ OIS::KC_UNASSIGNED, "<None>" },

		// Keyboard keys
		{ OIS::KC_ESCAPE, "Esc" },
		{ OIS::KC_1, "1" },
		{ OIS::KC_2, "2" },
		{ OIS::KC_3, "3" },
		{ OIS::KC_4, "4" },
		{ OIS::KC_5, "5" },
		{ OIS::KC_6, "6" },
		{ OIS::KC_7, "7" },
		{ OIS::KC_8, "8" },
		{ OIS::KC_9, "9" },
		{ OIS::KC_0, "0" },
		{ OIS::KC_MINUS, "-" },
		{ OIS::KC_EQUALS, "+" },
		{ OIS::KC_BACK, "Back" },
		{ OIS::KC_TAB, "Tab" },
		{ OIS::KC_Q, "Q" },
		{ OIS::KC_W, "W" },
		{ OIS::KC_E, "E" },
		{ OIS::KC_R, "R" },
		{ OIS::KC_T, "T" },
		{ OIS::KC_Y, "Y" },
		{ OIS::KC_U, "U" },
		{ OIS::KC_I, "I" },
		{ OIS::KC_O, "O" },
		{ OIS::KC_P, "P" },
		{ OIS::KC_LBRACKET, "[" },
		{ OIS::KC_RBRACKET, "]" },
		{ OIS::KC_RETURN, "Enter" },
		{ OIS::KC_LCONTROL, "Ctrl" },
		{ OIS::KC_A, "A" },
		{ OIS::KC_S, "S" },
		{ OIS::KC_D, "D" },
		{ OIS::KC_F, "F" },
		{ OIS::KC_G, "G" },
		{ OIS::KC_H, "H" },
		{ OIS::KC_J, "J" },
		{ OIS::KC_K, "K" },
		{ OIS::KC_L, "L" },
		{ OIS::KC_SEMICOLON, ";" },
		{ OIS::KC_APOSTROPHE, "'" },
		{ OIS::KC_GRAVE, "`" },
		{ OIS::KC_LSHIFT, "Shift" },
		{ OIS::KC_BACKSLASH, "Back Slash" },
		{ OIS::KC_Z, "Z" },
		{ OIS::KC_X, "X" },
		{ OIS::KC_C, "C" },
		{ OIS::KC_V, "V" },
		{ OIS::KC_B, "B" },
		{ OIS::KC_N, "N" },
		{ OIS::KC_M, "M" },
		{ OIS::KC_COMMA, "," },
		{ OIS::KC_PERIOD, "." },
		{ OIS::KC_SLASH, "/" },
		{ OIS::KC_RSHIFT, "Shift" },
		{ OIS::KC_MULTIPLY, "Pad X" },
		{ OIS::KC_LMENU, "Alt" },
		{ OIS::KC_SPACE, "Space" },
		{ OIS::KC_CAPITAL, "Caps Lock" },
		{ OIS::KC_F1, "F1" },
		{ OIS::KC_F2, "F2" },
		{ OIS::KC_F3, "F3" },
		{ OIS::KC_F4, "F4" },
		{ OIS::KC_F5, "F5" },
		{ OIS::KC_F6, "F6" },
		{ OIS::KC_F7, "F7" },
		{ OIS::KC_F8, "F8" },
		{ OIS::KC_F9, "F9" },
		{ OIS::KC_F10, "F10" },
		{ OIS::KC_NUMLOCK, "Num Lock" },
		{ OIS::KC_SCROLL, "Scroll Lock" },
		{ OIS::KC_NUMPAD7, "Pad 7" },
		{ OIS::KC_NUMPAD8, "Pad 8" },
		{ OIS::KC_NUMPAD9, "Pad 9" },
		{ OIS::KC_SUBTRACT, "Pad -" },
		{ OIS::KC_NUMPAD4, "Pad 4" },
		{ OIS::KC_NUMPAD5, "Pad 5" },
		{ OIS::KC_NUMPAD6, "Pad 6" },
		{ OIS::KC_ADD, "Pad +" },
		{ OIS::KC_NUMPAD1, "Pad 1" },
		{ OIS::KC_NUMPAD2, "Pad 2" },
		{ OIS::KC_NUMPAD3, "Pad 3" },
		{ OIS::KC_NUMPAD0, "Pad 0" },
		{ OIS::KC_DECIMAL, "Pad ." },
		{ OIS::KC_OEM_102, "\\" },
		{ OIS::KC_F11, "F11" },
		{ OIS::KC_F12, "F12" },
		{ OIS::KC_NUMPADENTER, "Pad Enter" },
		{ OIS::KC_RCONTROL, "Ctrl" },
		{ OIS::KC_DIVIDE, "Pad /" },
		{ OIS::KC_RMENU, "Alt" },
		{ OIS::KC_HOME, "Home" },
		{ OIS::KC_UP, "Up" },
		{ OIS::KC_PGUP, "Page Up" },
		{ OIS::KC_LEFT, "Left" },
		{ OIS::KC_RIGHT, "Right" },
		{ OIS::KC_END, "End" },
		{ OIS::KC_DOWN, "Down" },
		{ OIS::KC_PGDOWN, "Page Down" },
		{ OIS::KC_INSERT, "Insert" },
		{ OIS::KC_DELETE, "Del" },

		// Mouse keys
		{ MK_LCLICK, "Left-Click" },
		{ MK_RCLICK, "Right-Click" },
		{ MK_MCLICK, "Middle-Click" },
		{ MK_BUTTON_4, "Mouse 4" },
		{ MK_BUTTON_5, "Mouse 5" },
		{ MK_BUTTON_6, "Mouse 6" },
		{ MK_BUTTON_7, "Mouse 7" },
		{ MK_BUTTON_8, "Mouse 8" },
		{ MK_AXIS_X_NEG, "Mouse X-" },
		{ MK_AXIS_X_POS, "Mouse X+" },
		{ MK_AXIS_Y_NEG, "Mouse Y-" },
		{ MK_AXIS_Y_POS, "Mouse Y+" },
		{ MK_AXIS_Z_NEG, "Mouse Z-" },
		{ MK_AXIS_Z_POS, "Mouse Z+" },

		// TODO: When SDL is integrated, this can be refactored to pick names depending
		// on the type of controller connected (XBox, Nintendo, DualShock). -- Sezz 2025.03.05
		// Gamepad keys
		{ GK_BUTTON_1, "Gamepad 1" },
		{ GK_BUTTON_2, "Gamepad 2" },
		{ GK_BUTTON_3, "Gamepad 3" },
		{ GK_BUTTON_4, "Gamepad 4" },
		{ GK_BUTTON_5, "Gamepad 5" },
		{ GK_BUTTON_6, "Gamepad 6" },
		{ GK_BUTTON_7, "Gamepad 7" },
		{ GK_BUTTON_8, "Gamepad 8" },
		{ GK_BUTTON_9, "Gamepad 9" },
		{ GK_BUTTON_10, "Gamepad 10" },
		{ GK_BUTTON_11, "Gamepad 11" },
		{ GK_BUTTON_12, "Gamepad 12" },
		{ GK_BUTTON_13, "Gamepad 13" },
		{ GK_BUTTON_14, "Gamepad 14" },
		{ GK_BUTTON_15, "Gamepad 15" },
		{ GK_BUTTON_16, "Gamepad 16" },
		{ GK_AXIS_X_NEG, "Stick X-" },
		{ GK_AXIS_X_POS, "Stick X+" },
		{ GK_AXIS_Y_NEG, "Stick Y-" },
		{ GK_AXIS_Y_POS, "Stick Y+" },
		{ GK_AXIS_Z_NEG, "Stick Z-" },
		{ GK_AXIS_Z_POS, "Stick Z+" },
		{ GK_AXIS_W_NEG, "Stick W-" },
		{ GK_AXIS_W_POS, "Stick W+" },
		{ GK_AXIS_L_TRIGGER_1, "Left Trigger 1" },
		{ GK_AXIS_L_TRIGGER_2, "Left Trigger 2" },
		{ GK_AXIS_R_TRIGGER_1, "Right Trigger 1" },
		{ GK_AXIS_R_TRIGGER_2, "Right Trigger 2" },
		{ GK_DPAD_UP, "D-Pad Up" },
		{ GK_DPAD_DOWN, "D-Pad Down" },
		{ GK_DPAD_LEFT, "D-Pad Left" },
		{ GK_DPAD_RIGHT, "D-Pad Right" }
	};

	const std::string& GetKeyName(int keyID)
	{
		// Find and return key name.
		auto it = KEY_NAME_MAP.find(keyID);
		if (it != KEY_NAME_MAP.end())
		{
			const auto& [keyID, name] = *it;
			return name;
		}

		return KEY_NAME_MAP.at(OIS::KC_UNASSIGNED);
	}
}
