name: Bug report
description: Create a report to help us understand and triage your issue.
title: ""
labels: 
  - Awaiting Triage

body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report

        Please follow this document carefully to report a bug.

        > **Important**: It is highly recommended that you use the latest version before submitting a bug report.

  - type: dropdown
    attributes:
      label: TombEngine Version
      description: |
        Please select the TombEngine version you are using.
      options:
        - v1.8.1 (latest release)
        - v1.8.0
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Development Version
      description: Are you submitting this report from a development build that has not been officially released?
      options: 
        - label: Yes
        - label: No
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the Bug
      description: |
        Please provide a clear and concise description of what the issue is.
      placeholder: |
        Your bug report here.
    validations:
      required: true

  - type: textarea
    attributes:
      label: To Reproduce
      description: |
        Please provide detailed steps to reproduce the issue.
        
        **Note**: If the bug cannot be reproduced or the issue is not clearly explained, it may be closed without further investigation.
      placeholder: |
        Step-by-step reproduction instructions here.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behaviour
      description: |
        What did you expect to happen?

        **Note**: If the bug cannot be reproduced or the issue is not clearly explained, it may be closed without further investigation.
      placeholder: |
        A description of what should happen here.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Minimal Reproduction Project
      description: |
        Please upload a .zip file (10 MB max) containing your level and all assets needed to compile the level, including a minimal version where the bug occurs.

        Alternatively, provide a download link from a cloud storage service (e.g., Google Drive, Dropbox).

        > **Important**: If you do not provide a minimal reproduction project, your issue may be rejected.
      placeholder: |
        Download link to your project or attach a .zip file.
    validations:
      required: true
