name: Feature Request
description: Suggest an idea for TombEngine
title: "[ Feature Request ] "
labels: Awaiting Triage

body:

- type: textarea
  attributes:
    label: Is your feature request related to a problem? Please describe.
    placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  validations:
    required: true

- type: textarea
  attributes:
    label: Describe the solution you'd like
    placeholder: A clear and concise description of what you want to happen.
  validations:
    required: true

- type: textarea
  attributes:
    label: Describe alternatives you've considered
    placeholder: A clear and concise description of any alternative solutions or features you've considered.
  validations:
    required: false

- type: textarea
  attributes:
    label: Additional context
    placeholder: Add any other context or screenshots about the feature request here. (as a link to screenshot or drop the screenshot into this textbox)
  validations:
    required: false
