#pragma once

namespace TEN::Entities::TR4
{
	enum STATES_SKELETON
	{
		STATE_SKELETON_UNDER_FLOOR = 0,
		STATE_SKELETON_STOP = 1,
		STATE_SKELETON_AVOID_ATTACK1 = 5,
		STATE_SKELETON_AVOID_ATTACK2 = 6,
		STATE_SKELETON_USE_SHIELD = 7,
		STATE_SKELETON_ATTACK1 = 8,
		STATE_SKELETON_ATTACK2 = 9,
		STATE_SKELETON_ATTACK3 = 10,
		STATE_SKELETON_HURT_BY_SHOTGUN1 = 12,
		STATE_SKELETON_HURT_BY_SHOTGUN2 = 13,
		STATE_SKELETON_JUMP_LEFT = 19,
		STATE_SKELETON_JUMP_RIGHT = 20,
		STATE_SKELETON_JUMP_1SECTOR = 21,
		STATE_SKELETON_JUMP_2SECTORS = 22,
		STATE_SKELETON_JUMP_LIE_DOWN = 25
	};

	void InitialiseSkeleton(short itemNumber);
	void SkeletonControl(short itemNumber);
}