#pragma once
#include "global.h"

extern int NextBat;
extern BAT_STRUCT* Bats;
extern int NextSpider;
extern SPIDER_STRUCT* Spiders;
extern int NextRat;
extern RAT_STRUCT* Rats;

void InitialiseGuard(short itemNum);
void InitialiseSniper(short itemNum);
void InitialiseGuardLaser(short itemNum);
void InitialiseSubmarine(short itemNum);
void InitialiseDoberman(short itemNum);
void InitialiseDog(short itemNum);
void InitialiseReaper(short itemNum);
void InitialiseLarson(short itemNum);
void InitialiseHitman(short itemNum);
void InitialiseHydra(short itemNum);
void InitialiseImp(short itemNum);
void InitialiseLightingGuide(short itemNum);
void InitialiseBrownBeast(short itemNum);
void InitialiseInvisibleGhost(short itemNum);
void InitialiseGladiator(short itemNum);
/// void InitialiseRomanStatue(short itemNum)
void InitialiseAutoGuns(short itemNum);
void InitialisePushableBlock(short itemNum);
void ClearMovableBlockSplitters(int x, int y, int z, short roomNumber);
void PushableBlockControl(short itemNumber);
void PushableBlockCollision(short itemNum, ITEM_INFO* laraitem, COLL_INFO* coll);
int TestBlockMovable(ITEM_INFO* item, int blokhite);
int TestBlockPush(ITEM_INFO* item, int blokhite, unsigned short quadrant);
int TestBlockPull(ITEM_INFO* item, int blokhite, short quadrant);
void GuardControl(short itemNum);
void ControlDoberman(short itemNumber);
void ControlReaper(short itemNumber);
void SniperControl(short itemNumber);
void ImpThrowStones(ITEM_INFO* item);
void ControlImp(short itemNumber);
void ControlGladiator(short itemNumber);
void ControlBrowsBeast(short itemNumber);
void ControlInvisibleGhost(short itemNumber);
short GetNextRat();
void ControlLittleRats(short itemNumber);
void InitialiseMafia2(short itemNum);
void Mafia2Control(short itemNum);
void ControlDog(short itemNumber);
void ControlLarson(short itemNumber);
void InitialiseRaisingBlock(short itemNumber);
void ControlRaisingBlock(short itemNumber);
void InitialiseTeethSpikes(short itemNumber);
int CollidedWithTeethSpikes(ITEM_INFO* item);
void ControlTeethSpikes(short itemNumber);
void PulseLightControl(short itemNumber);
void TriggerAlertLight(int x, int y, int z, int r, int g, int b, int rot, __int16 roomNumber, __int16 falloff);
void StrobeLightControl(short itemNumber);
void ColorLightControl(short itemNumber);
void ElectricalLightControl(short itemNumber);
void BlinkingLightControl(short itemNumber);
void InitialiseTwoBlocksPlatform(short itemNumber);
void TwoBlocksPlatformControl(short itemNumber);
void TwoBlocksPlatformFloor(ITEM_INFO* item, int x, int y, int z, int* height);
void TwoBlocksPlatformCeiling(ITEM_INFO* item, int x, int y, int z, int* height);
int IsOnTwoBlocksPlatform(ITEM_INFO* item, int x, int z);
void InitialiseRaisingCog(short itemNumber);
void RaisingCogControl(short itemNumber);
void TriggerElectricityWiresSparks(int x, int z, char objNum, char node, int flags);
void TriggerLaraElectricitySparks(int flame);
int ElectricityWireCheckDeadlyBounds(PHD_VECTOR* pos, short delta);
void ElectricityWiresControl(short itemNumber);
void InitialiseRomeHammer(short itemNumber);
void InitialiseSmokeEmitter(short itemNumber);
void SmokeEmitterControl(short itemNumber);
void RomanStatueHitEffect(ITEM_INFO* item, PHD_VECTOR* pos, int joint);
void TriggerRomanStatueShockwaveAttackSparks(int x, int y, int z, byte r, byte g, byte b, byte size);
void TriggerRomanStatueScreamingSparks(int x, int y, int z, short xv, short yv, short zv, int flags);
void TriggerRomanStatueAttackEffect1(short itemNum, int factor);
void RomanStatueAttack(PHD_3DPOS* pos, short roomNumber, short count);
void TriggerRomanStatueMissileSparks(PHD_VECTOR* pos, char fxObj);
void InitialiseRomanStatue(short itemNum);
void ControlRomanStatue(short itemNumber);
void InitialiseTeleporter(short itemNumber);
void ControlTeleporter(short itemNumber);
void InitialiseHighObject1(short itemNumber);
void ControlHighObject1(short itemNumber);
void VentilatorEffect(short* bounds, int intensity, short rot, int speed);
void InitialiseVentilator(short itemNumber);
void VentilatorControl(short itemNumber);
void GenSlot1Control(short itemNumber);
void InitialiseGenSlot3(short itemNumber);
void DartControl(short itemNumber);
void DartEmitterControl(short itemNumber);
void FallingCeilingControl(short itemNumber);
void RollingBallCollision(short itemNumber, ITEM_INFO* l, COLL_INFO* coll);
void RollingBallControl(short itemNumber);
void DeathSlideCollision(short itemNumber, ITEM_INFO* l, COLL_INFO* coll);
void ControlDeathSlide(short itemNumber);
void InitialiseDeathSlide(short itemNumber);
void ControlSubmarine(short itemNumber);
void TriggerTorpedoBubbles(PHD_VECTOR* pos1, PHD_VECTOR* pos2, char factor);
void TriggerSubmarineSparks(short itemNumber);
void SubmarineAttack(ITEM_INFO* item);
void TriggerTorpedoSparks2(PHD_VECTOR* pos1, PHD_VECTOR* pos2, char scale);
void ChaffFlareControl(short itemNumber);
void TorpedoControl(short itemNumber);
void InitialiseLittleBats(short itemNumber);
void ControlLittleBats(short itemNumber);
short GetNextBat();
void TriggerLittleBat(ITEM_INFO* item);
void TriggerHitmanSparks(int x, int y, int z, short xv, short yv, short zv);
void HitmanControl(short itemNumber);
void ControlGunShip(short itemNumber);
void ControlHydra(short itemNumber);
void TriggerHydraSparks(short itemNumber, int frame);
void HydraBubblesAttack(PHD_3DPOS* pos, short roomNumber, int count);
void TriggerHydraMissileSparks(PHD_VECTOR* pos, short xv, short yv, short zv);
void TriggerAutoGunSmoke(PHD_VECTOR* pos, char shade);
void ControlAutoGuns(short itemNumber);
void TriggerGuardianSparks(PHD_VECTOR* pos, int count, byte r, byte g, byte b, int unk);
void GuardianCharge(ITEM_INFO* item);
short GetNextSpider();
void ControlSpiders(short itemNumber);
void InitialiseSpiders(short itemNumber);
void ClearSpidersPatch(ITEM_INFO* item);
void ClearSpiders();
void InitialiseLittleRats(short itemNumber);
void ClearRats();
void UpdateSpiders();
void UpdateRats();
void UpdateBats();
void MissileControl(short itemNumber);
void InitialiseGuardian(short itemNumber);
void GuardianControl(short itemNumber);
void ControlBodyPart(short fxNumber);
void ExplodeFX(FX_INFO* fx, int noXZVel, int bits);
void InitialiseLagoonWitch(short itemNumber);
void ControlLagoonWitch(short itemNumber);
void InitialiseChef(short itemNumber);
void ControlChef(short itemNumber);
void InitialiseLion(short itemNum);
void LionControl(short itemNum);
