return {
    {
        type = "diary",
        object = TEN.Objects.ObjID.DIARY_ITEM,
        objectIdBg = TEN.Objects.ObjID.CUSTOM_BAR_GRAPHIC,
        spriteIdBg = 0,
        colorBg = TEN.Color(255, 255, 255),
        pos = TEN.Vec2(50,50),
        rot = 0,
        scale = TEN.Vec2(100,100),
        alignMode = TEN.View.AlignMode.CENTER,
        scaleMode = TEN.View.ScaleMode.FIT,
        blendMode = TEN.Effects.BlendID.ALPHABLEND,
        alpha = 255,
        pageSound=369,
        exitSound=369,
        pagesToUnlock = 1
    },
    {
        type = "background",
        objectIdBg = TEN.Objects.ObjID.CUSTOM_BAR_GRAPHIC,
        spriteIdBg = 6,
        colorBg = TEN.Color(255,0, 0),
        pos = TEN.Vec2(50,50),
        rot = 0,
        scale = TEN.Vec2(100,100),
        alignMode = TEN.View.AlignMode.CENTER,
        scaleMode = TEN.View.ScaleMode.STRETCH,
        blendMode = TEN.Effects.BlendID.ALPHABLEND,
        alpha = 160
    },
    {
        type = "pageNumbers",
        pageNoType = 2,
        prefix = "Page: ",
        separator = " of ",
        textPos = TEN.Vec2(5,95),
        textOptions = {TEN.Strings.DisplayStringOption.CENTER, TEN.Strings.DisplayStringOption.SHADOW},
        textScale = 1,
        textColor = TEN.Color(255, 0, 0)
    },
    {
        type = "controls",
        string1 = "Space: Play Voice Note",
        string2 = "Left Key: Previous Page",
        string3 = "Right Key: Next Page",
        string4 = "Esc: Back",
        textPos = TEN.Vec2(5,95),
        textOptions = {TEN.Strings.DisplayStringOption.CENTER, TEN.Strings.DisplayStringOption.SHADOW},
        textScale = 1,
        textColor = TEN.Color(255, 0, 0)
    },
    {
        type = "notification",
        notificationTime = 3,
        objectId = TEN.Objects.ObjID.CUSTOM_BAR_GRAPHIC,
        spriteId = 5,
        color = TEN.Color(255,255,255),
        pos = TEN.Vec2(90,90),
        rot = 0,
        scale = TEN.Vec2(5,5),
        alignMode = TEN.View.AlignMode.CENTER,
        scaleMode = TEN.View.ScaleMode.STRETCH,
        blendMode = TEN.Effects.BlendID.ALPHABLEND,
        notificationSound = 114 
    },
    {
        type = "image",
        pageIndex = 1,
        objectIdBg = TEN.Objects.ObjID.CUSTOM_BAR_GRAPHIC,
        spriteIdBg = 1,
        colorBg = TEN.Color(255, 255, 255),
        pos = TEN.Vec2(25,50),
        rot = 0,
        scale = TEN.Vec2(20,20),
        alignMode = TEN.View.AlignMode.CENTERLEFT,
        scaleMode = TEN.View.ScaleMode.FIT,
        blendMode = TEN.Effects.BlendID.ALPHABLEND
    },
    {
        type = "text",
        pageIndex = 1,
        text = "The fire came and I was stuck",
        textPos = TEN.Vec2(56,10),
        textOptions = {TEN.Strings.DisplayStringOption.SHADOW},
        textScale = 1,
        textColor = TEN.Color(255, 255, 255)
    },
    {
        type = "narration",
        pageIndex = 1,
        trackName = "027",
    },
    {
        type = "image",
        pageIndex = 2,
        objectIdBg = TEN.Objects.ObjID.CUSTOM_BAR_GRAPHIC,
        spriteIdBg = 2,
        colorBg = TEN.Color(255, 255, 255),
        pos = TEN.Vec2(25,50),
        rot = 0,
        scale = TEN.Vec2(20,20),
        alignMode = TEN.View.AlignMode.CENTER,
        scaleMode = TEN.View.ScaleMode.FIT,
        blendMode = TEN.Effects.BlendID.ALPHABLEND
    },
    {
        type = "text",
        pageIndex = 2,
        text = "The fire came and I was stuck \nand there was nothing I could do to escape but nothing can be done\n about it now",
        textPos = TEN.Vec2(56,10),
        textOptions = {TEN.Strings.DisplayStringOption.SHADOW},
        textScale = 1,
        textColor = TEN.Color(128, 255, 128)
    },
    {
        type = "text",
        pageIndex = 2,
        text = "We tried running\nbut in vain",
        textPos = TEN.Vec2(56,10),
        textOptions = {TEN.Strings.DisplayStringOption.RIGHT, TEN.Strings.DisplayStringOption.BLINK},
        textScale = 0.5,
        textColor = TEN.Color(128, 255, 128)
    },
    {
        type = "narration",
        pageIndex = 2,
        trackName = "032",
    },
    {
        type = "image",
        pageIndex = 3,
        objectIdBg = TEN.Objects.ObjID.CUSTOM_BAR_GRAPHIC,
        spriteIdBg = 2,
        colorBg = TEN.Color(255, 255, 255),
        pos = TEN.Vec2(25,20),
        rot = 0,
        scale = TEN.Vec2(20,20),
        alignMode = TEN.View.AlignMode.CENTER,
        scaleMode = TEN.View.ScaleMode.FIT,
        blendMode = TEN.Effects.BlendID.ALPHABLEND
    },
    {
        type = "image",
        pageIndex = 3,
        objectIdBg = TEN.Objects.ObjID.CUSTOM_BAR_GRAPHIC,
        spriteIdBg = 2,
        colorBg = TEN.Color(255, 255, 255),
        pos = TEN.Vec2(25,90),
        rot = 0,
        scale = TEN.Vec2(10,10),
        alignMode = TEN.View.AlignMode.CENTERLEFT,
        scaleMode = TEN.View.ScaleMode.FIT,
        blendMode = TEN.Effects.BlendID.ALPHABLEND
    },
    {
        type = "text",
        pageIndex = 3,
        text = "Save me Seemore",
        textPos = TEN.Vec2(56,10),
        textOptions = {TEN.Strings.DisplayStringOption.BLINK},
        textScale = 1,
        textColor = TEN.Color(128, 255, 128)
    },
    {
        type = "text",
        pageIndex = 3,
        text = "No escape\nonly despair",
        textPos = TEN.Vec2(85,54),
        textOptions = {TEN.Strings.DisplayStringOption.RIGHT},
        textScale = 2,
        textColor = TEN.Color(255, 128, 64)
    },
    {
        type = "narration",
        pageIndex = 3,
        trackName = "053",
    },
    {
        type = "image",
        pageIndex = 4,
        objectIdBg = TEN.Objects.ObjID.CUSTOM_BAR_GRAPHIC,
        spriteIdBg = 1,
        colorBg = TEN.Color(255, 255, 255),
        pos = TEN.Vec2(25,50),
        rot = 0,
        scale = TEN.Vec2(40,40),
        alignMode = TEN.View.AlignMode.CENTERLEFT,
        scaleMode = TEN.View.ScaleMode.STRETCH,
        blendMode = TEN.Effects.BlendID.ALPHABLEND
    },
    {
        type = "image",
        pageIndex = 4,
        objectIdBg = TEN.Objects.ObjID.CUSTOM_BAR_GRAPHIC,
        spriteIdBg = 2,
        colorBg = TEN.Color(255, 255, 255),
        pos = TEN.Vec2(25,90),
        rot = 0,
        scale = TEN.Vec2(10,10),
        alignMode = TEN.View.AlignMode.CENTERLEFT,
        scaleMode = TEN.View.ScaleMode.FIT,
        blendMode = TEN.Effects.BlendID.ALPHABLEND
    },
    {
        type = "text",
        pageIndex = 4,
        text = "Nobody came to save me",
        textPos = TEN.Vec2(56,10),
        textOptions = {TEN.Strings.DisplayStringOption.SHADOW},
        textScale = 1,
        textColor = TEN.Color(255, 0, 0)
    },
    {
        type = "text",
        pageIndex = 4,
        text = "So I have to save myself",
        textPos = TEN.Vec2(56,25),
        textOptions = {TEN.Strings.DisplayStringOption.BLINK},
        textScale = 1,
        textColor = TEN.Color(128, 255, 128)
    },
    {
        type = "text",
        pageIndex = 4,
        text = "I will fight for myself",
        textPos = TEN.Vec2(85,80),
        textOptions = {TEN.Strings.DisplayStringOption.RIGHT},
        textScale = 2,
        textColor = TEN.Color(128, 128, 255)
    },
}