#pragma once
#include <stdlib.h>
#include <stdio.h>
#include <stdint.h>
#include <memory>
#include <functional>
#include <vector>
#include <map>
#include <string>
#include <array>
#include <d3d11.h>
#include <optional>
//#include <SimpleMath.h>
//#include "Game/debug/debug.h"
#include <algorithm>
#include <set>
#include "framework.h"
#include <sol.hpp>

